name: Download data for loaded-dice-calc-server

on:
  push:
    branches:
      - main

jobs:
  download-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v3

      # Docker image
      - name: Login to the container registry.
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the docker image and push it to the container registry.
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/dotkuro/loaded-dice-calc-data-downloader:latest

      # Kubernetes job
      - name: Install doctl.
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Download kubectl config.
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 60 k8s-private-apps
      - name: Delete old runs of the same job
        run: |
          kubectl delete -f deployments/kubernetes/data-downloader-job.yaml
      - name: Apply the job manifest.
        run: |
          kubectl apply -f deployments/kubernetes/data-downloader-job.yaml

