name: Download data for loaded-dice-calc-server

# Running on pull_request for now for debugging purposes
# on:
#   push:
#     branches:
#       - main
on: pull_request

jobs:
  download-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v3
      - name: Login to the container registry.
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the docker image and push it to the container registry.
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/dotkuro/loaded-dice-calc-data-downloader:latest
